Fixes ticket #89.
core/console_mode.py:

	run(): uses the map returned by the interpreter instead of
	looking at the obj id, since that is actually the
	persistent_id, and probably doesn't match the local one.

	TestConsoleMode.test_dynamic_module_error: new test

core/modules/vistrails_module.py:

	DummyModuleLogging: new class

	Module.__init__: self.logging defaults to an instance of
	DummyModuleLogging.

	Module.clear: reset self.logging to the default

	Module.update(): 

            checking for self._logger is no longer needed.

	    check for a dynamic module raising ModuleError, capture
	    this ModuleError, wrap it into a pipeline module and
	    re-raise.

	Module.requestOutputFromPort(): added missing self reference
	to Module.

tests/resources/console_mode_test.py:

	TestDynamicModuleError: new module

tests/resources/pythonsource.xml: fixed test
tests/resources/dynamic_module_error.xml: new test vistrail