Fixed a bug in QCellContainer
takeWidget() called deleteLater() on the widget anyway, causing a
RuntimeError: "wrapped C/C++ object of type RichTextCellWidget has been
deleted" in sip.