-- Progress towards easier package installation/configuration. Work on the package and configuration dialog.
New feature: packages will be configurable by creating a
ConfigurationObject and storing it as 'configuration' in the
package. I'll write about it in the users guide.

Package docstrings show up as "description" on the package tab
under Edit -> Preferences, so we probably need to put nice docstring
in our VisTrails packages. I added a VTK one.
--

core/packagemanager.py:

	Package._get_configuration: new method

	Package.configuration: new property

	Package._get_description: new method

	Package.description: new property

	PackageManager.PackageInternalError: new exception

	PackageManager.get_package_configuration: new method

	PackageManager.installed_package_list: new method

gui/configuration.py: new file with widgets to display and edit
configuration objects

gui/preferences.py:

	Moved all general configuration widgets to gui/configuration.py

	QPackagesWidget: new class

	QPreferencesDialog.create_packages_tab: new method

	QPreferencesDialog.__init__: created packages tab.

packages/vtk/__init__.py: Added docstring.