-- Added get_current_vistrail_view, undo and redo to api.
Major performance gains for undo/redo. Undo is now 10 times faster
(undoing 100 actions on one leaf of terminator.vt took 30 seconds, now
does around ~3) than it was this morning, mostly by being careful
about repeated calls to functions and not recomputing things
repeatedly. I'll work more on redo tomorrow.

Many minor changes in many places, see list below.

more work on doc/signal_mess.txt
--

api/__init__.py:

	undo: new function

	redo: new function

	get_current_vistrail_view: new function

core/data_structures/graph.py:

	GraphException: new Exception (other graph exceptions subclass
	from this)

	Graph.delete_vertex: pop -> del

	Graph.rename_vertex: new method

	TestGraph.test_rename_vertex: new test

core/data_structures/point.py:

	Point.show_comparison: fix compare

	Point.__eq__: performance: don't instantiate new point

core/vistrail/location.py:

	Added tests to exercise point behavior

	performance: Uses db_* to skip some of the property lookups
	
	Location.__eq__: performance: don't instantiate new location

core/vistrail/vistrail.py:

	Added test to make sure getPipeline fails with parameter -1

db/services/vistrail.py:

	materializeWorkflow: raise VistrailsDBException when given
	invalid workflow version

gui/builder_window.py:

	QBuilderWindow.vistrailViewAdded: force recompute of bounding
	box on fitToView

gui/graphics_view.py:

	QInteractiveGraphicsScene.fitToView: takes extra parameter
	that controls call to updateSceneBoundingRect. This prevents
	this function from being repeatedly called.

	QInteractiveGraphicsScene.fitToAllViews: takes extra parameter
	that controls call to updateSceneBoundingRect. This prevents
	this function from being repeatedly called.

	QInteractiveGraphicsView.keyPressEvent: forces call to
	updateSceneBoundingRect.

	QInteractiveGraphicsView.showEvent: forces call to
	updateSceneBoundingRect.

gui/pipeline_tab.py:

	QPipelineTab.versionChanged: don't fit to views here, done
	elsewhere in the code.

gui/pipeline_view.py:

	QPipelineScene.setupScene: don't fit to views here, done
	elsewhere in the code.

gui/version_tab.py:

	QVersionTab.versionSelected: forces call to
	updateSceneBoundingRect.

gui/version_view.py:

	QGraphicsVersionTextItem.changed: only call reset if some
	of the values changed.

gui/vis_diff.py:

	QVisualDiff.createDiffPipeline: forces call to
	updateSceneBoundingRect.

gui/vistrail_controller.py:

	VistrailController.changeSelectedVersion: performance: do not
	create copy of pipeline before performing actions.

	VistrailController.recompute_terse_graph: performance: small
	tweaks

	VistrailController.showPreviousVersion: performance: do not
	call getVersionGraph - use _current_full_graph. performance:
	when we know how the terse graph will change, don't recompute
	it, simply update it.