ModuleError: documentation ModuleError.__init__: documentation Module: documentation Module.is_cacheable(): new method. Module.__str__(): improvement in string representation for debugging Module.getInputFromPort: Uses ModuleError instead of Exception