<bugfix>Argument error caused gui/vistrail_controller test to fail</bugfix>
gui/vistrail_controller.py:
- VistrailController.add_module: added self as first argument to BaseController.add_module call

These were the errors:
======================================================================
ERROR: test_group (gui.pipeline_view.TestPipelineView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Applications/VisTrails/Vistrails.app/Contents/Resources/lib/python2.7/gui/pipeline_view.py", line 2737, in test_group
    m1 = api.add_module(0, 0,    'edu.utah.sci.vistrails.basic', 'File', '')
  File "/Applications/VisTrails/Vistrails.app/Contents/Resources/lib/python2.7/api/__init__.py", line 135, in add_module
    result = controller.add_module(x, y, identifier, name, namespace)
  File "/Applications/VisTrails/Vistrails.app/Contents/Resources/lib/python2.7/gui/vistrail_controller.py", line 262, in add_module
    internal_version)
TypeError: unbound method add_module() must be called with VistrailController instance as first argument (got str instance instead)

======================================================================
ERROR: test_create_functions (gui.vistrail_controller.TestVistrailController)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Applications/VisTrails/Vistrails.app/Contents/Resources/lib/python2.7/gui/vistrail_controller.py", line 1335, in test_create_functions
    'ConcatenateString')
  File "/Applications/VisTrails/Vistrails.app/Contents/Resources/lib/python2.7/gui/vistrail_controller.py", line 262, in add_module
    internal_version)
TypeError: unbound method add_module() must be called with VistrailController instance as first argument (got str instance instead)
----------------------------------------------------------------------