-- New directory vistrails/api, which includes standalone functions that help third-party applications that need an API into VisTrails.
Changed some more methods to their correct naming conventions.

Fixed file changed issue: now VistrailController.changed is not set
every time an action is performed - it is set when a new action is
added (or tags are changed, etc)

Started putting signals emitted by class on the docstring - this will
hopefully help alleviate the signal mess that we're in right now.
Added file doc/signal_mess.txt, where people are welcome to add their
own documentation about the spaghetti of signals we got ourselves in :)

VistrailController now always stores a copy of the current
full and terse graph, so that invalidations that don't involve
recomputing the layout are faster. In the future, this will allow
undo/redo without recomputing the layout, which will be much faster,
if my preliminary tests are to be trusted.
--

core/data_structures/graph.py:

	Graph.parent(): now raises VertexHasNoParentError and KeyError
	instead of returning 0 and -1 respectively, since these might
	be actual vertex ids.

	Graph.VertexHasNoParentError: new exception

	TestGraph.test_parent_source: new test

core/vistrail/vistrail.py:

	Vistrail.get_latest_version(): new method

gui/view_manager.py:

	QViewManager.addVistrailView renamed to add_vistrail_view

	QViewManager.newVistrail(): removed duplicate code with
	setVistrailView

	QViewManager.setVistrailView: renamed to
	set_vistrail_view. calls setup_view instead of setOpenView or
	setInitialView, since the two functions were identical.

	QViewManager.open_vistrail: removed code that checks
	temporaries, since it's now consolidated at
	QVistrailView.setVistrail

gui/vistrail_controller.py:

	Expanded VistrailController's docstring to include emitted
	signals.

	VistrailController.setVistrail: calls recompute_terse_graph

	VistrailController.perform_action: do not set changed to True.

	VistrailController.add_new_action: new function that add a new
	action and updates the state accordingly (like self.changed
	and the current full and terse graphs). This function should
	be called every time the controller wants to add a new action
	to the vistrail.

	VistrailController.add_module: uses add_new_action

	VistrailController.deleteModuleList: uses add_new_action

	VistrailController.moveModuleList: uses add_new_action

	VistrailController.add_connection: uses add_new_action

	VistrailController.deleteConnectionList: uses add_new_action

	VistrailController.addMethod: uses add_new_action

	VistrailController.replace_method: uses add_new_action

	VistrailController.deleteAnnotation: uses add_new_action

	VistrailController.addAnnotation: uses add_new_action

	VistrailController.addModulePort: uses add_new_action

	VistrailController.deleteModulePort: uses add_new_action

	VistrailController.recompute_terse_graph: new method, uses
	most of the code from refineGraph.

	VistrailController.refineGraph: now simply returns the current
	full and terse graphs

	VistrailController.showPreviousVersion: updates logic to
	behave differently under refined views.

	VistrailController.perform_param_changes: uses add_new_action,
	added docstring and warning (since this function only gets
	called from the spreadsheet, do we really need it?)

	VistrailController.performBulkActions: removed method that
	was not used throughout VisTrails.

	VistrailController.pasteModulesAndConnections: uses
	add_new_action

	VistrailController.create_group: uses add_new_action

	VistrailController.ungroup: uses add_new_action

	VistrailController.create_abstraction: calls setChanged(true),
	uses add_new_action

gui/vistrail_view.py:

	QVistrailView.setInitialView: removed method

	QVistrailView.setOpenView: removed method

	QVistrailView.setup_view: new method that subsumes
	setInitialView and setOpenView, since those two methods really
	behaved exactly the same (the docstrings were lying).

	
api: new directory

api/__init__.py: new file